
### Get workouts
GET http://localhost:8000/workouts/

### Get single Workout
GET http://localhost:8000/workouts/674c83e8f5f71568591a0919


### Insert Workout
POST http://localhost:8000/workouts 
content-type: application/json

{
    "title": "Push Ups",
    "reps": 15,
    "loads": 4
}



### Update Workout
PUT http://localhost:8000/workouts/674c83e8f5f71568591a0919
content-type: application/json

{
    "title": "Pull Ups",
    "reps": 3,
    "loads": 9
}





### Delete Workout
DELETE http://localhost:8000/workouts/674c874489bc4c44a8d0a2b1





