
### Get workouts
GET http://localhost:8000/workouts/
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NzRjYjY0Y2YyNmY5Y2YzZjMyZGRjZGQiLCJpYXQiOjE3MzMxNzIxNjAsImV4cCI6MTczMzE3NTc2MH0.B469eoZtBGoi__MVYZEXUqbBtbxIWmqyoX2jno1wU_8


### Get single Workout
GET http://localhost:8000/workouts/674c83e8f5f71568591a0919
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NzRjYjY0Y2YyNmY5Y2YzZjMyZGRjZGQiLCJpYXQiOjE3MzMxNzIxNjAsImV4cCI6MTczMzE3NTc2MH0.B469eoZtBGoi__MVYZEXUqbBtbxIWmqyoX2jno1wU_8



### Insert Workout
POST http://localhost:8000/workouts 
content-type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NzRjYjY0Y2YyNmY5Y2YzZjMyZGRjZGQiLCJpYXQiOjE3MzMxNzIxNjAsImV4cCI6MTczMzE3NTc2MH0.B469eoZtBGoi__MVYZEXUqbBtbxIWmqyoX2jno1wU_8


{
    "title": "Push Ups",
    "reps": 15,
    "loads": 4
}



### Update Workout
PUT http://localhost:8000/workouts/674c83e8f5f71568591a0919
content-type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NzRjYjY0Y2YyNmY5Y2YzZjMyZGRjZGQiLCJpYXQiOjE3MzMxNzIxNjAsImV4cCI6MTczMzE3NTc2MH0.B469eoZtBGoi__MVYZEXUqbBtbxIWmqyoX2jno1wU_8


{
    "title": "Pull Ups",
    "reps": 3,
    "loads": 9
}





### Delete Workout
DELETE http://localhost:8000/workouts/674c874489bc4c44a8d0a2b1
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NzRjYjY0Y2YyNmY5Y2YzZjMyZGRjZGQiLCJpYXQiOjE3MzMxNzIxNjAsImV4cCI6MTczMzE3NTc2MH0.B469eoZtBGoi__MVYZEXUqbBtbxIWmqyoX2jno1wU_8






